/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CourseRouteImport } from './routes/_course'
import { Route as CourseIndexRouteImport } from './routes/_course/index'
import { Route as CourseSettingsRouteImport } from './routes/_course/settings'
import { Route as CourseConceptB8RouteImport } from './routes/_course/concept/b8'
import { Route as CourseConceptB7RouteImport } from './routes/_course/concept/b7'
import { Route as CourseConceptB6RouteImport } from './routes/_course/concept/b6'
import { Route as CourseConceptB5RouteImport } from './routes/_course/concept/b5'
import { Route as CourseConceptB4RouteImport } from './routes/_course/concept/b4'
import { Route as CourseConceptB3RouteImport } from './routes/_course/concept/b3'
import { Route as CourseConceptB2RouteImport } from './routes/_course/concept/b2'
import { Route as CourseConceptB1RouteImport } from './routes/_course/concept/b1'

const CourseRoute = CourseRouteImport.update({
  id: '/_course',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRoute,
} as any)
const CourseSettingsRoute = CourseSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB8Route = CourseConceptB8RouteImport.update({
  id: '/concept/b8',
  path: '/concept/b8',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB7Route = CourseConceptB7RouteImport.update({
  id: '/concept/b7',
  path: '/concept/b7',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB6Route = CourseConceptB6RouteImport.update({
  id: '/concept/b6',
  path: '/concept/b6',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB5Route = CourseConceptB5RouteImport.update({
  id: '/concept/b5',
  path: '/concept/b5',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB4Route = CourseConceptB4RouteImport.update({
  id: '/concept/b4',
  path: '/concept/b4',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB3Route = CourseConceptB3RouteImport.update({
  id: '/concept/b3',
  path: '/concept/b3',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB2Route = CourseConceptB2RouteImport.update({
  id: '/concept/b2',
  path: '/concept/b2',
  getParentRoute: () => CourseRoute,
} as any)
const CourseConceptB1Route = CourseConceptB1RouteImport.update({
  id: '/concept/b1',
  path: '/concept/b1',
  getParentRoute: () => CourseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CourseIndexRoute
  '/settings': typeof CourseSettingsRoute
  '/concept/b1': typeof CourseConceptB1Route
  '/concept/b2': typeof CourseConceptB2Route
  '/concept/b3': typeof CourseConceptB3Route
  '/concept/b4': typeof CourseConceptB4Route
  '/concept/b5': typeof CourseConceptB5Route
  '/concept/b6': typeof CourseConceptB6Route
  '/concept/b7': typeof CourseConceptB7Route
  '/concept/b8': typeof CourseConceptB8Route
}
export interface FileRoutesByTo {
  '/settings': typeof CourseSettingsRoute
  '/': typeof CourseIndexRoute
  '/concept/b1': typeof CourseConceptB1Route
  '/concept/b2': typeof CourseConceptB2Route
  '/concept/b3': typeof CourseConceptB3Route
  '/concept/b4': typeof CourseConceptB4Route
  '/concept/b5': typeof CourseConceptB5Route
  '/concept/b6': typeof CourseConceptB6Route
  '/concept/b7': typeof CourseConceptB7Route
  '/concept/b8': typeof CourseConceptB8Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_course': typeof CourseRouteWithChildren
  '/_course/settings': typeof CourseSettingsRoute
  '/_course/': typeof CourseIndexRoute
  '/_course/concept/b1': typeof CourseConceptB1Route
  '/_course/concept/b2': typeof CourseConceptB2Route
  '/_course/concept/b3': typeof CourseConceptB3Route
  '/_course/concept/b4': typeof CourseConceptB4Route
  '/_course/concept/b5': typeof CourseConceptB5Route
  '/_course/concept/b6': typeof CourseConceptB6Route
  '/_course/concept/b7': typeof CourseConceptB7Route
  '/_course/concept/b8': typeof CourseConceptB8Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/concept/b1'
    | '/concept/b2'
    | '/concept/b3'
    | '/concept/b4'
    | '/concept/b5'
    | '/concept/b6'
    | '/concept/b7'
    | '/concept/b8'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/concept/b1'
    | '/concept/b2'
    | '/concept/b3'
    | '/concept/b4'
    | '/concept/b5'
    | '/concept/b6'
    | '/concept/b7'
    | '/concept/b8'
  id:
    | '__root__'
    | '/_course'
    | '/_course/settings'
    | '/_course/'
    | '/_course/concept/b1'
    | '/_course/concept/b2'
    | '/_course/concept/b3'
    | '/_course/concept/b4'
    | '/_course/concept/b5'
    | '/_course/concept/b6'
    | '/_course/concept/b7'
    | '/_course/concept/b8'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CourseRoute: typeof CourseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_course': {
      id: '/_course'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_course/': {
      id: '/_course/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/settings': {
      id: '/_course/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CourseSettingsRouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b8': {
      id: '/_course/concept/b8'
      path: '/concept/b8'
      fullPath: '/concept/b8'
      preLoaderRoute: typeof CourseConceptB8RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b7': {
      id: '/_course/concept/b7'
      path: '/concept/b7'
      fullPath: '/concept/b7'
      preLoaderRoute: typeof CourseConceptB7RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b6': {
      id: '/_course/concept/b6'
      path: '/concept/b6'
      fullPath: '/concept/b6'
      preLoaderRoute: typeof CourseConceptB6RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b5': {
      id: '/_course/concept/b5'
      path: '/concept/b5'
      fullPath: '/concept/b5'
      preLoaderRoute: typeof CourseConceptB5RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b4': {
      id: '/_course/concept/b4'
      path: '/concept/b4'
      fullPath: '/concept/b4'
      preLoaderRoute: typeof CourseConceptB4RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b3': {
      id: '/_course/concept/b3'
      path: '/concept/b3'
      fullPath: '/concept/b3'
      preLoaderRoute: typeof CourseConceptB3RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b2': {
      id: '/_course/concept/b2'
      path: '/concept/b2'
      fullPath: '/concept/b2'
      preLoaderRoute: typeof CourseConceptB2RouteImport
      parentRoute: typeof CourseRoute
    }
    '/_course/concept/b1': {
      id: '/_course/concept/b1'
      path: '/concept/b1'
      fullPath: '/concept/b1'
      preLoaderRoute: typeof CourseConceptB1RouteImport
      parentRoute: typeof CourseRoute
    }
  }
}

interface CourseRouteChildren {
  CourseSettingsRoute: typeof CourseSettingsRoute
  CourseIndexRoute: typeof CourseIndexRoute
  CourseConceptB1Route: typeof CourseConceptB1Route
  CourseConceptB2Route: typeof CourseConceptB2Route
  CourseConceptB3Route: typeof CourseConceptB3Route
  CourseConceptB4Route: typeof CourseConceptB4Route
  CourseConceptB5Route: typeof CourseConceptB5Route
  CourseConceptB6Route: typeof CourseConceptB6Route
  CourseConceptB7Route: typeof CourseConceptB7Route
  CourseConceptB8Route: typeof CourseConceptB8Route
}

const CourseRouteChildren: CourseRouteChildren = {
  CourseSettingsRoute: CourseSettingsRoute,
  CourseIndexRoute: CourseIndexRoute,
  CourseConceptB1Route: CourseConceptB1Route,
  CourseConceptB2Route: CourseConceptB2Route,
  CourseConceptB3Route: CourseConceptB3Route,
  CourseConceptB4Route: CourseConceptB4Route,
  CourseConceptB5Route: CourseConceptB5Route,
  CourseConceptB6Route: CourseConceptB6Route,
  CourseConceptB7Route: CourseConceptB7Route,
  CourseConceptB8Route: CourseConceptB8Route,
}

const CourseRouteWithChildren =
  CourseRoute._addFileChildren(CourseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CourseRoute: CourseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
